In [1]:
import pandas as pd

In [2]:
#from google.colab import drive
#drive.mount('/content/drive/')
#%cd /content/drive/My Drive/Colab Notebooks/ICD

TT_2020 = pd.read_csv('../data/TikTok_songs_2020.csv')
TT_2021 = pd.read_csv('../data/TikTok_songs_2021.csv')
TT_2022 = pd.read_csv('../data/TikTok_songs_2022.csv')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).
/content/drive/My Drive/Colab Notebooks/ICD

In [7]:
# TT_2020 = pd.read_csv('TikTok_songs_2020.csv')
# TT_2021 = pd.read_csv('TikTok_songs_2021.csv')
# TT_2022 = pd.read_csv('TikTok_songs_2022.csv')

TT_2020['year'] = 2020
TT_2021['year'] = 2021
TT_2022['year'] = 2022

In [8]:
TT_2020.head()

,track_name,artist_name,artist_pop,album,track_pop,danceability,energy,loudness,mode,key,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,duration_ms,year
0,Say So,Doja Cat,88,Hot Pink,80,0.787,0.673,-4.583,0,11,0.1590,0.26400,0.000003,0.0904,0.779,110.962,4,237893,2020
1,Blinding Lights,The Weeknd,93,After Hours,90,0.514,0.730,-5.934,1,1,0.0598,0.00146,0.000095,0.0897,0.334,171.005,4,200040,2020
2,Supalonely (feat. Gus Dapperton),BENEE,67,Hey u x,63,0.862,0.631,-4.746,1,7,0.0515,0.29100,0.000209,0.1230,0.841,128.978,4,223488,2020
3,Savage,Megan Thee Stallion,82,Suga,70,0.843,0.741,-5.609,1,11,0.3340,0.02520,0.000000,0.0960,0.680,168.983,4,155497,2020
4,Moral of the Story,Ashe,68,Moral of the Story,76,0.572,0.406,-8.624,1,10,0.0427,0.58700,0.000004,0.1020,0.265,119.812,4,201084,2020

In [9]:
TT_2021.head()

,track_name,artist_name,artist_pop,album,track_pop,danceability,energy,loudness,mode,key,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,duration_ms,year
0,STAY (with Justin Bieber),The Kid LAROI,83,STAY (with Justin Bieber),89,0.591,0.764,-5.484,1,1,0.0483,0.0383,0.000000,0.1030,0.478,169.928,4,141806,2021
1,Peaches (feat. Daniel Caesar & Giveon),Justin Bieber,90,Justice,86,0.677,0.696,-6.181,1,0,0.1190,0.3210,0.000000,0.4200,0.464,90.030,4,198082,2021
2,edamame (feat. Rich Brian),bbno$,72,edamame (feat. Rich Brian),77,0.815,0.848,-4.704,0,4,0.1150,0.0230,0.000162,0.0265,0.684,106.032,4,133707,2021
3,Here's Your Perfect,Jamie Miller,65,Here's Your Perfect,77,0.558,0.454,-5.335,1,6,0.0551,0.4990,0.000000,0.1460,0.424,113.120,4,158594,2021
4,It's You,Sezairi,57,It's You,73,0.630,0.456,-8.285,1,8,0.0317,0.5450,0.000000,0.1140,0.166,137.915,3,251440,2021

In [10]:
TT_2022.head()

,track_name,artist_name,artist_pop,album,track_pop,danceability,energy,loudness,mode,key,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,duration_ms,year
0,Running Up That Hill (A Deal With God),Kate Bush,81,Hounds Of Love,95,0.629,0.547,-13.123,0,10,0.0550,0.7200,0.003140,0.0604,0.197,108.375,4,298933,2022
1,As It Was,Harry Styles,91,As It Was,96,0.520,0.731,-5.338,0,6,0.0557,0.3420,0.001010,0.3110,0.662,173.930,4,167303,2022
2,Sunroof,Nicky Youre,73,Sunroof,44,0.768,0.716,-5.110,1,10,0.0404,0.3500,0.000000,0.1500,0.841,131.430,4,163026,2022
3,Heat Waves,Glass Animals,80,Dreamland (+ Bonus Levels),89,0.761,0.525,-6.900,1,11,0.0944,0.4400,0.000007,0.0921,0.531,80.870,4,238805,2022
4,About Damn Time,Lizzo,81,About Damn Time,92,0.836,0.743,-6.305,0,10,0.0656,0.0995,0.000000,0.3350,0.722,108.966,4,191822,2022

In [11]:
TT = pd.concat([TT_2020, TT_2021, TT_2022])
TT.head()

,track_name,artist_name,artist_pop,album,track_pop,danceability,energy,loudness,mode,key,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,duration_ms,year
0,Say So,Doja Cat,88,Hot Pink,80,0.787,0.673,-4.583,0,11,0.1590,0.26400,0.000003,0.0904,0.779,110.962,4,237893,2020
1,Blinding Lights,The Weeknd,93,After Hours,90,0.514,0.730,-5.934,1,1,0.0598,0.00146,0.000095,0.0897,0.334,171.005,4,200040,2020
2,Supalonely (feat. Gus Dapperton),BENEE,67,Hey u x,63,0.862,0.631,-4.746,1,7,0.0515,0.29100,0.000209,0.1230,0.841,128.978,4,223488,2020
3,Savage,Megan Thee Stallion,82,Suga,70,0.843,0.741,-5.609,1,11,0.3340,0.02520,0.000000,0.0960,0.680,168.983,4,155497,2020
4,Moral of the Story,Ashe,68,Moral of the Story,76,0.572,0.406,-8.624,1,10,0.0427,0.58700,0.000004,0.1020,0.265,119.812,4,201084,2020

In [12]:
TT.tail()

,track_name,artist_name,artist_pop,album,track_pop,danceability,energy,loudness,mode,key,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,duration_ms,year
258,The Less I Know The Better,Tame Impala,78,Currents,84,0.640,0.740,-4.083,1,4,0.0284,0.011500,0.006780,0.1670,0.785,116.879,4,216320,2022
259,Dandelions,Ruth B.,75,Safe Haven,90,0.609,0.692,-2.958,1,1,0.0259,0.015700,0.000000,0.0864,0.454,116.959,3,233720,2022
260,Jimmy Cooks (feat. 21 Savage),Drake,95,"Honestly, Nevermind",92,0.529,0.673,-4.711,1,0,0.1750,0.000307,0.000002,0.0930,0.366,165.921,4,218365,2022
261,Good Looking,Suki Waterhouse,64,Good Looking,80,0.377,0.558,-9.076,1,4,0.0299,0.078900,0.000342,0.1250,0.267,149.971,3,214800,2022
262,INFERNO,Sub Urban,67,INFERNO,71,0.820,0.611,-5.020,0,9,0.1220,0.076600,0.000025,0.0684,0.637,127.883,4,133134,2022

In [14]:
TT_2020.describe()

,artist_pop,track_pop,danceability,energy,loudness,mode,key,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,duration_ms,year
count,292.000000,292.00000,292.000000,292.000000,292.000000,292.000000,292.000000,292.000000,292.000000,292.000000,292.000000,292.000000,292.000000,292.000000,292.000000,292.0
mean,67.318493,61.19863,0.725404,0.612855,-6.884469,0.534247,5.041096,0.150245,0.232500,0.028654,0.187648,0.545168,119.770538,3.945205,192805.212329,2020.0
std,16.571140,20.78498,0.143129,0.163366,2.697198,0.499682,3.689638,0.150504,0.255970,0.114149,0.141949,0.212719,25.609372,0.316354,55763.157757,0.0
min,0.000000,0.00000,0.174000,0.045800,-23.928000,0.000000,0.000000,0.025900,0.000041,0.000000,0.021900,0.038900,71.994000,1.000000,37632.000000,2020.0
25%,57.750000,57.00000,0.651000,0.489250,-8.369750,0.000000,1.000000,0.045200,0.027050,0.000000,0.095175,0.389750,100.064000,4.000000,158673.000000,2020.0
50%,69.000000,66.00000,0.734500,0.631000,-6.523000,1.000000,5.000000,0.084650,0.129000,0.000000,0.124000,0.554500,119.967000,4.000000,191130.000000,2020.0
75%,80.000000,74.00000,0.831750,0.729000,-4.983500,1.000000,8.000000,0.217000,0.329250,0.000196,0.251000,0.712750,131.334750,4.000000,221394.750000,2020.0
max,95.000000,90.00000,0.980000,0.955000,-2.607000,1.000000,11.000000,0.907000,0.974000,0.856000,0.944000,0.967000,210.857000,5.000000,467587.000000,2020.0

In [15]:
TT_2021.describe()

,artist_pop,track_pop,danceability,energy,loudness,mode,key,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,duration_ms,year
count,190.000000,190.000000,190.000000,190.000000,190.000000,190.000000,190.000000,190.000000,190.000000,190.000000,190.000000,190.000000,190.000000,190.000000,190.000000,190.0
mean,70.878947,65.578947,0.708105,0.672700,-5.929774,0.621053,4.894737,0.093522,0.204124,0.007814,0.176361,0.563204,125.533495,3.957895,194612.563158,2021.0
std,15.301246,22.917417,0.116882,0.149721,2.305945,0.486407,3.661537,0.092847,0.222932,0.052535,0.129755,0.213829,26.832668,0.322549,38899.194512,0.0
min,0.000000,0.000000,0.386000,0.184000,-17.667000,0.000000,0.000000,0.025900,0.000079,0.000000,0.026500,0.034800,65.043000,1.000000,80118.000000,2021.0
25%,63.000000,63.000000,0.651000,0.578250,-7.040750,0.000000,1.000000,0.041825,0.020350,0.000000,0.093225,0.412750,107.978000,4.000000,169067.000000,2021.0
50%,73.500000,73.000000,0.710000,0.692000,-5.703000,1.000000,5.000000,0.055700,0.119000,0.000000,0.118000,0.584000,122.975000,4.000000,195806.500000,2021.0
75%,82.000000,79.000000,0.784250,0.790000,-4.322750,1.000000,8.000000,0.096925,0.320250,0.000036,0.240000,0.750750,138.041750,4.000000,218103.500000,2021.0
max,95.000000,91.000000,0.949000,0.989000,-1.609000,1.000000,11.000000,0.505000,0.837000,0.611000,0.825000,0.970000,206.072000,5.000000,344571.000000,2021.0

In [16]:
TT_2022.describe()

,artist_pop,track_pop,danceability,energy,loudness,mode,key,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,duration_ms,year
count,263.000000,263.000000,263.000000,263.000000,263.000000,263.000000,263.000000,263.000000,263.000000,263.000000,263.000000,263.000000,263.000000,263.000000,263.000000,263.0
mean,64.186312,59.844106,0.715338,0.682631,-6.300513,0.536122,5.809886,0.117268,0.193188,0.020244,0.202562,0.506149,122.883696,3.969582,174656.212928,2022.0
std,18.146338,24.976524,0.117722,0.141756,1.905114,0.499644,3.657312,0.101417,0.214588,0.109370,0.151808,0.220757,24.396686,0.288168,34785.125564,0.0
min,18.000000,0.000000,0.308000,0.214000,-13.468000,0.000000,0.000000,0.025200,0.000038,0.000000,0.026500,0.036300,62.948000,1.000000,85742.000000,2022.0
25%,50.000000,47.000000,0.646000,0.593000,-7.423500,0.000000,2.000000,0.044750,0.028100,0.000000,0.094350,0.349000,106.850500,4.000000,148646.000000,2022.0
50%,64.000000,66.000000,0.726000,0.701000,-6.067000,1.000000,6.000000,0.070700,0.120000,0.000003,0.132000,0.485000,123.056000,4.000000,171028.000000,2022.0
75%,81.000000,79.500000,0.796500,0.790500,-4.887000,1.000000,9.000000,0.156000,0.298500,0.000334,0.277500,0.680000,130.004500,4.000000,199047.000000,2022.0
max,95.000000,97.000000,0.961000,0.955000,-2.634000,1.000000,11.000000,0.481000,0.965000,0.939000,0.790000,0.956000,187.906000,5.000000,298933.000000,2022.0

In [17]:
TT.describe()

,artist_pop,track_pop,danceability,energy,loudness,mode,key,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,duration_ms,year
count,745.000000,745.000000,745.000000,745.000000,745.000000,745.000000,745.000000,745.000000,745.000000,745.000000,745.000000,745.000000,745.000000,745.000000,745.000000,745.000000
mean,67.120805,61.837584,0.717439,0.652750,-6.434842,0.557047,5.275168,0.124137,0.211385,0.020371,0.190034,0.535993,122.339293,3.957047,186859.185235,2020.961074
std,17.014902,22.961145,0.128110,0.155729,2.371747,0.497069,3.687853,0.123269,0.234037,0.100384,0.142755,0.216822,25.579655,0.308102,45919.355116,0.862815
min,0.000000,0.000000,0.174000,0.045800,-23.928000,0.000000,0.000000,0.025200,0.000038,0.000000,0.021900,0.034800,62.948000,1.000000,37632.000000,2020.000000
25%,57.000000,53.000000,0.650000,0.542000,-7.636000,0.000000,1.000000,0.043900,0.024800,0.000000,0.094400,0.383000,103.991000,4.000000,157712.000000,2020.000000
50%,69.000000,69.000000,0.725000,0.673000,-6.135000,1.000000,5.000000,0.069700,0.123000,0.000000,0.125000,0.531000,121.932000,4.000000,181733.000000,2021.000000
75%,81.000000,78.000000,0.802000,0.773000,-4.753000,1.000000,8.000000,0.164000,0.316000,0.000160,0.260000,0.711000,134.002000,4.000000,214137.000000,2022.000000
max,95.000000,97.000000,0.980000,0.989000,-1.609000,1.000000,11.000000,0.907000,0.974000,0.939000,0.944000,0.970000,210.857000,5.000000,467587.000000,2022.000000

In [18]:
TT.dropna(inplace=True)
TT.reset_index(drop=True, inplace=True)
TT.tail()

,track_name,artist_name,artist_pop,album,track_pop,danceability,energy,loudness,mode,key,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,duration_ms,year
740,The Less I Know The Better,Tame Impala,78,Currents,84,0.640,0.740,-4.083,1,4,0.0284,0.011500,0.006780,0.1670,0.785,116.879,4,216320,2022
741,Dandelions,Ruth B.,75,Safe Haven,90,0.609,0.692,-2.958,1,1,0.0259,0.015700,0.000000,0.0864,0.454,116.959,3,233720,2022
742,Jimmy Cooks (feat. 21 Savage),Drake,95,"Honestly, Nevermind",92,0.529,0.673,-4.711,1,0,0.1750,0.000307,0.000002,0.0930,0.366,165.921,4,218365,2022
743,Good Looking,Suki Waterhouse,64,Good Looking,80,0.377,0.558,-9.076,1,4,0.0299,0.078900,0.000342,0.1250,0.267,149.971,3,214800,2022
744,INFERNO,Sub Urban,67,INFERNO,71,0.820,0.611,-5.020,0,9,0.1220,0.076600,0.000025,0.0684,0.637,127.883,4,133134,2022